### ISSUE TITLE
社區網路封面無法顯示於臉書

### ISSUE THREAD

**Issue by littlesea922** [tainansprout/tainan-council-watch#266]
### 問題描述

1. 社區網路封面（網址縮圖）無法顯示於臉書，之前將圖片完全調整為建議大小的1200X628像素，曾一度（3/29）可顯示；4/6再新增文章發佈，發現無法顯示；而原先的文章也無法顯示

<img width="624" alt="截圖 2023-04-06 下午3 37 35" src="https://user-images.githubusercontent.com/105342746/230311050-26de87f5-0138-4a06-a5e7-fc13e57e4997.png">

<img width="577" alt="截圖 2023-04-06 下午3 38 10 1" src="https://user-images.githubusercontent.com/105342746/230311108-8cc354a1-763a-48b4-95de-d32861036933.png">

臉書截圖的原文章
https://tcco.tnsprout.org/article/look20230217

新增的網址
https://tcco.tnsprout.org/article/look20230330

### 系統資訊

- 使用的瀏覽器（附上版本為佳）:Google Chrome 版本 111.0.5563.146 (正式版本) (x86_64) 
- 使用的作業系統： MacOS Monterey 版本12.6.3(21G419)
- 使用的設備：MAC筆電

### 問題產生的步驟

若有明確產生問題的步驟，請條列在此

**Comment by ddio** [comment]
@littlesea922  現在有了，看起來是 FB 不喜歡中文檔名的封面圖片，改用英數字就可以了。
