### ISSUE TITLE
第三屆第六次定期會的「發言開頭」，皆未顯示在網站

### ISSUE THREAD

**Issue by littlesea922** [tainansprout/tainan-council-watch#269]
### 問題描述
第三屆第六次定期會的「發言開頭」，皆未顯示在網站
（應與長度無關）

<img width="1021" alt="截圖 2023-05-03 下午3 54 45" src="https://user-images.githubusercontent.com/105342746/235861799-df470f33-0871-438e-86b0-9b799cc3c4d0.png">

<img width="1636" alt="截圖 2023-05-03 下午3 55 04" src="https://user-images.githubusercontent.com/105342746/235861835-60cbf87c-fb2d-446d-8c5d-e8ecaee73643.png">

[網頁](https://tcco.tnsprout.org/3rd/interpellation?query=%E8%B3%AA%E7%96%91%E6%8F%90%E5%8D%87%E6%96%B0%E4%BD%8F%E6%B0%91%E5%AD%90%E5%A5%B3%E8%AA%AA%E6%AF%8D%E8%AA%9E%E7%9A%84%E6%94%BF%E7%AD%96%E7%9B%AE%E6%A8%99%E5%90%AB%E7%B3%8A%EF%BC%8C%E5%A6%82%E6%9E%9C%E5%AD%B8%E7%94%9F%E6%98%AF%E5%8F%AF%E4%BB%A5%E9%81%B8%E6%93%87%E5%AD%B8%E7%BF%92%E9%9D%9E%E6%AF%8D%E8%AA%9E%E7%9A%84%E5%A4%96%E8%AA%9E%EF%BC%8C%E9%82%A3%E5%B0%B1%E4%B8%8D%E5%BF%85%E5%BC%B7%E8%AA%BF%E6%AF%8D%E8%AA%9E%E9%80%99%E5%80%8B%E6%A8%99%E7%B1%A4%E3%80%82&catType=null)

[資料](https://docs.google.com/spreadsheets/d/1AGfPR2JxCSr5tVH0Cn6qUuk1fvknQIROSGmS0l_bxQM/edit#gid=8326131)

**Comment by ddio** [comment]
@littlesea922  ，因為第六次的資料欄位有誤，開頭幾句話的欄位名稱應該是「發言開頭2句話」，而不是「發言開頭幾句話（勿跨頁）」。

資料庫同步資料時，會以欄位名稱，而非欄位順序為依據呦，請勿隨意更改欄位名稱。

資料已經更新完成，網站[可以搜尋到了](https://tcco.tnsprout.org/3rd/interpellation/?query=%E8%A6%81%E6%B1%82%E5%B8%82%E5%BA%9C%E6%AF%94%E7%85%A7%E5%85%B6%E4%BB%96%E7%B8%A3%E5%B8%82%E6%8F%90%E9%AB%98%E4%BA%94%E5%80%8D%E5%88%B8&catType=null)，再過半小時會完成所有網站頁面更新～
